class _BotCommands:
    def __init__(self):
        self.StartCommand = 'betastart'
        self.MirrorCommand = 'betamirror'
        self.UnzipMirrorCommand = 'betaunzipmirror'
        self.TarMirrorCommand = 'betatarmirror'
        self.CancelMirror = 'betacancel'
        self.CancelAllCommand = 'betacancelall'
        self.StatusCommand = 'betastatus'
        self.AuthorizedUsersCommand = 'betausers'
        self.StatsCommand = 'betastats'
        self.HelpCommand = 'betahelp'
        self.SpeedCommand = 'betaspeedtest'
        self.CloneCommand = 'betaclone'
        self.CountCommand = 'betacount'
        self.WatchCommand = 'betawatch'
        self.TarWatchCommand = 'betatarwatch'
        self.DeleteCommand = 'betadel'
        self.UsageCommand = 'betausage'
        self.ListCommand = 'list'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.RestartCommand = 'restart'
        self.PingCommand = 'ping'
        self.LogCommand = 'log'
        self.MediaInfoCommand = 'mediainfo'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update'


BotCommands = _BotCommands()
